#!/bin/bash

workspaces() {

  # Danh sách workspace
  ws1="1"
  ws2="2"
  ws3="3"
  ws4="4"
  ws5="5"
  ws6="6"

  # Kiểm tra workspace nào đang được sử dụng
  o1=$(hyprctl workspaces | grep "$ws1")
  o2=$(hyprctl workspaces | grep "$ws2")
  o3=$(hyprctl workspaces | grep "$ws3")
  o4=$(hyprctl workspaces | grep "$ws4")
  o5=$(hyprctl workspaces | grep "$ws5")
  o6=$(hyprctl workspaces | grep "$ws6")

  # Kiểm tra workspace nào đang được focus
  f1=$(hyprctl activeworkspace | grep "$ws1")
  f2=$(hyprctl activeworkspace | grep "$ws2")
  f3=$(hyprctl activeworkspace | grep "$ws3")
  f4=$(hyprctl activeworkspace | grep "$ws4")
  f5=$(hyprctl activeworkspace | grep "$ws5")
  f6=$(hyprctl activeworkspace | grep "$ws6")

  echo "(box	:class \"works\" :orientation \"v\"	:halign \"center\"	:valign \"start\"	 :space-evenly \"false\" :spacing \"-5\" (button :onclick \"bspc desktop -f $ws1\"	:class	\"$un$o1$f1\"	\"\") (button :onclick \"bspc desktop -f $ws2\"	:class \"$un$o2$f2\"	 \"\") (button :onclick \"bspc desktop -f $ws3\"	:class \"$un$o3$f3\" \"\") (button :onclick \"bspc desktop -f $ws4\"	:class \"$un$o4$f4\"	\"\") (button :onclick \"bspc desktop -f $ws5\"	:class \"$un$o5$f5\" \"\" )  (button :onclick \"bspc desktop -f $ws6\"	:class \"$un$o6$f6\" \"\"))"

}

workspaces
hyprctl -j events | jq -r 'select(.event=="workspace" or .event=="movewindow")' | while read -r line; do
    workspaces
done
