
[window]
opacity = 0.5
blur = true

[font]
size = 12.0

[font.bold]
family = "JetBrainsMonoNerdFontMono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNerdFontMono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNerdFontMono"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNerdFontMono"
style = "Regular"
